# Test VietnamMarketDataService Data Query

Query FPT daily bars from `2014-01-01` inclusive to `2015-01-01` exclusive through the service API.

In [9]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

sys.path.insert(0, str(PROJECT_ROOT / "src"))
PROJECT_ROOT

WindowsPath('d:/vs code project/TechnicalResearch')

In [10]:
import json
import os
from urllib.request import urlopen

from dotenv import load_dotenv

load_dotenv(PROJECT_ROOT / ".env")

BASE_URL = os.getenv("VN_MARKET_DATA_API_URL", "http://127.0.0.1:8000").rstrip("/")
health = json.loads(urlopen(f"{BASE_URL}/api/v1/health", timeout=10).read().decode("utf-8"))
health

{'status': 'ok', 'version': 'v1'}

In [11]:
from loaders.market_data_api import load_market_bars

df = load_market_bars(
    symbols="FPT",
    start="2026-06-01",
    end="2026-06-19",
)

df.head()

         time symbol  open  high   low  close      volume source dataset
0  2026-06-01    FPT  72.2  73.4  72.1   72.9   5994107.0    VCI     raw
1  2026-06-02    FPT  73.0  75.6  73.0   74.8  17419530.0    VCI     raw
2  2026-06-03    FPT  75.1  77.7  75.0   76.5  25354808.0    VCI     raw
3  2026-06-04    FPT  76.7  77.2  75.8   76.1  11331159.0    VCI     raw
4  2026-06-05    FPT  76.0  76.0  74.3   75.0  11249802.0    VCI     raw

In [12]:
df.tail()

         time symbol  open  high   low  close      volume source dataset
1  2026-06-02    FPT  73.0  75.6  73.0   74.8  17419530.0    VCI     raw
2  2026-06-03    FPT  75.1  77.7  75.0   76.5  25354808.0    VCI     raw
3  2026-06-04    FPT  76.7  77.2  75.8   76.1  11331159.0    VCI     raw
4  2026-06-05    FPT  76.0  76.0  74.3   75.0  11249802.0    VCI     raw
5  2026-06-08    FPT  73.7  74.5  72.8   72.9  10914200.0    VCI     raw

In [13]:
summary = {
    "rows": len(df),
    "symbols": sorted(df["symbol"].dropna().unique().tolist()) if not df.empty else [],
    "min_time": df["time"].min() if not df.empty else None,
    "max_time": df["time"].max() if not df.empty else None,
}
summary

{'rows': 6,
 'symbols': ['FPT'],
 'min_time': '2026-06-01',
 'max_time': '2026-06-08'}

In [ ]:
if df.empty:
    raise AssertionError("No FPT rows returned. Check that the service is running and MongoDB contains FPT data for 2026.")

assert set(df["symbol"]) == {"FPT"}
assert df["time"].min() >= "2026-06-01"
assert df["time"].max() < "2026-06-19"
assert df["time"].is_monotonic_increasing

"FPT 2026 data query passed"

'FPT 2026 data query passed'